version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DB_SCHEMA=${POSTGRES_USER}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_USER}
      - DB_HOST=${POSTGRES_USER}
    depends_on:
      - db
    volumes:
      - ./:/opt/app/
      - /opt/app/node_modules

  db:
    build:
      context: .
      dockerfile: ./src/db/Dockerfile
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data 

networks:
  default:
    name: node_postgres_network