version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./src/db/Dockerfile
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    # depends_on:
    #   - db
    restart: always

volumes:
  db: